-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings

-   repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    -   id: black
        args: [--config=./pyproject.toml]

-   repo: https://github.com/PyCQA/isort
    rev: '5.7.0'
    hooks:
      - id: isort

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        exclude: ^tests/
