[tool.poetry]
name = "sixi-web"
version = "0.1.0"
description = ""
authors = ["liaoxingyi <liaoxingyi@douban.com>"]

[tool.poetry.dependencies]
python = "^3.9"
WebOb = "^1.8.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
watchdog = "^2.1.5"
gunicorn = "^20.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
